### ISSUE TITLE
bug: does not work in service workers

### ISSUE THREAD

**Issue by SgtPooki** [achingbrain/mortice#67]
When testing some code for ipfs-shipyard/helia-service-worker-gateway, we saw the following error:

```
heliaFetch.ts:106 fs.stat error for cid 'QmbSa3mkSjwTX32feHXC9yMZ6TVH2JzJdR5sHyzssJueLB' and path '/' TypeError: globalThis.postMessage is not a function
    at Object.readLock (browser.ts:67:16)
    at storage.ts:108:41
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (pins.ts:189:4)
    at _next (pins.ts:189:4)
    at pins.ts:189:4
    at new Promise (<anonymous>)
    at pins.ts:189:4
    at BlockStorage.get (storage.ts:125:6)
    at unixFsResolver (index.ts:32:34)

```

coming from https://github.com/achingbrain/mortice/blob/0eab826e744c8bc23ac65d17ac3a44e5f4694a3d/src/browser.ts#L67

We should move away from postMessage to [BroadcastChannel](https://developer.mozilla.org/en-US/docs/Web/API/Broadcast_Channel_API) and [MessageChannel](https://developer.mozilla.org/en-US/docs/Web/API/MessageChannel/MessageChannel) which should be supported in all browser contexts and node after v15.

**Comment by talentlessguy** [comment]
because of it, this also errors on Deno cuz `globalThis.postMessage` is undefined there

**Comment by achingbrain** [comment]
@talentlessguy does Deno support `BroadcastChannel`?  MDN says [no](https://developer.mozilla.org/en-US/docs/Web/API/Broadcast_Channel_API) but references an ancient version and it's in the [Deno docs](https://docs.deno.com/deploy/api/runtime-broadcast-channel/).

**Comment by talentlessguy** [comment]
this is Deno Deploy, not Deno itself afaik

**Comment by achingbrain** [comment]
Well spotted.  Do you know if Deno supports the `BroadcastChannel` and `MessageChannel` APIs?

**Comment by SgtPooki** [comment]
quick test:

## Deno

```shell
> deno run --allow-all channels_support.ts
Unsupported compiler options in "file:///Users/sgtpooki/code/work/ipshipyard/ipfs/service-worker-gateway/tsconfig.json".
  The following options were ignored:
    allowJs, ignoreDeprecations, module, moduleResolution, outDir, target
BroadcastChannel supported: false
MessageChannel   supported: true
MessageChannel received ▶ hello from MessageChannel

> deno --version
deno 2.3.1 (stable, release, aarch64-apple-darwin)
v8 13.5.212.10-rusty
typescript 5.8.3
```

## Bun

```shell
> bun channels_support.ts
BroadcastChannel supported: true
MessageChannel   supported: true
MessageChannel received ▶ hello from MessageChannel

> bun --version
1.2.13
```
